"""
Bundle engine — ``cup bundle`` re-export generation.

Scans a directory for codeupipe components and generates an
``__init__.py`` with clean re-exports.
"""

import ast
from pathlib import Path


def _extract_exports(filepath: Path) -> list:
    """Extract public classes and builder functions from a Python file using AST.

    Returns list of (symbol_name, kind) tuples where kind is 'class' or 'function'.
    """
    try:
        source = filepath.read_text()
        tree = ast.parse(source, filename=str(filepath))
    except (SyntaxError, OSError):
        return []

    exports = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            exports.append((node.name, "class"))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                exports.append((node.name, "function"))
    return exports


def bundle(directory: str) -> dict:
    """Scan a directory and generate __init__.py with re-exports.

    Returns dict with 'init_file' path and 'exports' list.
    """
    dir_path = Path(directory)
    if not dir_path.is_dir():
        raise FileNotFoundError(f"Directory not found: {directory}")

    all_exports = []
    for py_file in sorted(dir_path.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        module = py_file.stem
        symbols = _extract_exports(py_file)
        for symbol, kind in symbols:
            all_exports.append((module, symbol, kind))

    if not all_exports:
        raise ValueError(f"No exportable symbols found in {directory}")

    modules = {}
    for module, symbol, kind in all_exports:
        modules.setdefault(module, []).append(symbol)

    lines = ['"""', f"Public API for {dir_path.name} package.", "",
             "Auto-generated by: cup bundle", '"""', ""]
    for module in sorted(modules.keys()):
        symbols = sorted(modules[module])
        symbols_str = ", ".join(symbols)
        lines.append(f"from .{module} import {symbols_str}")

    all_symbols = sorted(sym for _, sym, _ in all_exports)
    lines.append("")
    lines.append("__all__ = [")
    for sym in all_symbols:
        lines.append(f'    "{sym}",')
    lines.append("]")
    lines.append("")

    init_content = "\n".join(lines)
    init_file = dir_path / "__init__.py"
    init_file.write_text(init_content)

    return {
        "init_file": str(init_file),
        "exports": [(m, s) for m, s, _ in all_exports],
    }
